# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Uo2tX17Xx1EU27lLFWIgRTygJ45zbV2o

#**Task**: Replace the unidentified values with mean values

##**Step 1**: Import the essential libraries and read the uploaded csv file

* copy the path from the uploaded file
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import *

ds=pd.read_csv("/content/sample_data/A_2018.02.02_11.21.55.csv")
ds

"""## **Step 2**: Describe the data set
* By this we'll be able to study the dataset
"""

ds.describe()

"""##**Step 2**: Replace the '-' with NaN values"""

symbol_to_replace="-"
ds.replace(symbol_to_replace, np.nan, inplace= True)
ds
ds.to_csv("/content/cleanedds.csv", index=False)

"""##**Step 3**: Now replace the NaN value of acquired column with the mean value of the entire column which is to be replaced"""

ds_1=pd.read_csv("/content/cleanedds.csv")

columns_to_replace = ['RSSI', 'NRxRSRP', 'NRxRSRQ']
ds_1[columns_to_replace] = ds_1[columns_to_replace].fillna(ds_1.mean())
ds_1
ds_1.to_csv("/content/final_ds.csv", index=False)

